/**
 * Mirrors app/schemas in apps/api. Field names here are camelCase because the
 * API's response models serialize that way (app/schemas/base.py's
 * CamelReadModel) while staying snake_case in Python — keep new types
 * matching that convention. Keep in sync by hand; there is no codegen step yet.
 */

export type AppLanguage = "en" | "hi" | "hinglish";

export type UserRole = "teacher" | "school_admin" | "super_admin";

export interface UserProfile {
  id: string;
  name: string;
  email: string | null;
  phone: string | null;
  role: UserRole;
  schoolId: string | null;
  preferredLanguage: AppLanguage;
  createdAt: string;
}

export interface CreateUserProfileInput {
  name: string;
  schoolId?: string;
  preferredLanguage: AppLanguage;
}

export interface School {
  id: string;
  name: string;
  state: string;
  district: string | null;
  block: string | null;
}

export interface Board {
  id: string;
  name: string;
  state: string;
}

export interface SchoolClass {
  id: string;
  boardId: string;
  grade: number;
  displayName: string;
}

export interface Subject {
  id: string;
  classId: string;
  name: string;
}

export interface Chapter {
  id: string;
  subjectId: string;
  name: string;
  sequenceNo: number | null;
  syllabusTopics: string[] | null;
}

export type DurationOption = "30" | "40" | "60";

export type TeachingMode = "story" | "activity" | "exam" | "concept" | "quick_revision";

export type ResourceType =
  | "lesson_plan"
  | "teaching_script"
  | "blackboard_notes"
  | "local_context"
  | "activities"
  | "questions"
  | "previous_year_questions"
  | "worksheet"
  | "presentation"
  | "mind_map"
  | "flowchart"
  | "diagram"
  | "audio"
  | "animation";

/** Resources generated by default for every kit until the rest leave "designed but not implemented" — see docs/07-roadmap.md. */
export const MVP_RESOURCE_TYPES: ResourceType[] = [
  "lesson_plan",
  "teaching_script",
  "questions",
  "worksheet",
  "presentation",
  "mind_map",
  "audio",
];

export type QuestionDifficulty = "easy" | "moderate" | "advanced";

export interface GenerationParams {
  classId: string;
  subjectId: string;
  chapterId: string;
  language: AppLanguage;
  duration: DurationOption;
  teachingMode: TeachingMode;
}

export interface GenerateTeachingKitRequest extends GenerationParams {
  rawQuery?: string;
  resourceTypes: ResourceType[];
}

export type KitStatus = "pending" | "generating" | "partial" | "complete" | "failed";

export interface TeachingKitRequestSummary {
  requestId: string;
  status: KitStatus;
  streamUrl: string;
}

export interface ResourceReadyEvent {
  resourceType: ResourceType;
  resourceId: string;
  cacheHit: boolean;
}
