/**
 * Mirrors app/schemas in apps/api. Field names here are camelCase because the
 * API's response models serialize that way (app/schemas/base.py's
 * CamelReadModel) while staying snake_case in Python — keep new types
 * matching that convention. Keep in sync by hand; there is no codegen step yet.
 */

export type AppLanguage = "en" | "hi" | "hinglish";

export type UserRole = "teacher" | "school_admin" | "super_admin";

export interface UserProfile {
  id: string;
  name: string;
  email: string | null;
  phone: string | null;
  role: UserRole;
  schoolId: string | null;
  preferredLanguage: AppLanguage;
  createdAt: string;
}

export interface CreateUserProfileInput {
  name: string;
  schoolId?: string;
  preferredLanguage: AppLanguage;
}

export interface School {
  id: string;
  name: string;
  state: string;
  district: string | null;
  block: string | null;
}

export interface Board {
  id: string;
  name: string;
  state: string;
}

export interface SchoolClass {
  id: string;
  boardId: string;
  grade: number;
  displayName: string;
}

export interface Subject {
  id: string;
  classId: string;
  name: string;
}

export interface Chapter {
  id: string;
  subjectId: string;
  name: string;
  sequenceNo: number | null;
  syllabusTopics: string[] | null;
}

/** For a subject the seed data doesn't cover yet — most of them, since only
 * Class 7 Science has a full seeded chapter list. Get-or-create on the
 * backend: an existing name (case-insensitive) returns that chapter rather
 * than forking the catalog. */
export interface CreateChapterInput {
  subjectId: string;
  name: string;
}

export type DurationOption = "30" | "40" | "60";

export type TeachingMode =
  "story" | "activity" | "exam" | "concept" | "quick_revision";

export type ResourceType =
  | "lesson_plan"
  | "teaching_script"
  | "blackboard_notes"
  | "local_context"
  | "activities"
  | "questions"
  | "previous_year_questions"
  | "worksheet"
  | "presentation"
  | "mind_map"
  | "flowchart"
  | "diagram"
  | "audio"
  | "animation";

/** Resources generated by default for every kit until the rest leave "designed but not implemented" — see docs/07-roadmap.md. */
export const MVP_RESOURCE_TYPES: ResourceType[] = [
  "lesson_plan",
  "teaching_script",
  "questions",
  "worksheet",
  "presentation",
  "mind_map",
  "audio",
];

export type QuestionDifficulty = "easy" | "moderate" | "advanced";

export interface GenerationParams {
  classId: string;
  subjectId: string;
  chapterId: string;
  language: AppLanguage;
  duration: DurationOption;
  teachingMode: TeachingMode;
}

export interface GenerateTeachingKitRequest extends GenerationParams {
  rawQuery?: string;
  resourceTypes: ResourceType[];
}

export type KitStatus =
  "pending" | "generating" | "partial" | "complete" | "failed";

export interface TeachingKitRequestSummary {
  requestId: string;
  status: KitStatus;
  streamUrl: string;
}

export interface ResourceReadyEvent {
  resourceType: ResourceType;
  resourceId: string;
  cacheHit: boolean;
}

export interface KitCompleteEvent {
  requestId: string;
  status: KitStatus;
  durationMs: number;
}

export interface GeneratedResource {
  id: string;
  resourceType: ResourceType;
  content: Record<string, unknown>;
  fileUrl: string | null;
  language: AppLanguage;
  cacheHit: boolean;
  createdAt: string;
}

export interface TeachingKitState {
  requestId: string;
  status: KitStatus;
  /** Denormalized on the API side so the result page can title itself without
   * three extra catalog round trips. */
  classDisplayName: string;
  subjectName: string;
  chapterName: string;
  language: AppLanguage;
  duration: DurationOption;
  teachingMode: TeachingMode;
  requestedResourceTypes: ResourceType[];
  resources: GeneratedResource[];
}

/* ---------------------------------------------------------------------------
 * Resource content shapes
 *
 * These mirror the Pydantic response schemas in apps/api/app/ai/prompts/*.py,
 * which are what the LLM is constrained to emit and what lands verbatim in
 * `generated_resources.content`. A `GeneratedResource` carries `content` as an
 * opaque record; narrow it with the matching type below once you know the
 * `resourceType`.
 *
 * Field names here stay snake_case, unlike the rest of this file: `content` is
 * stored jsonb that the API passes through untouched, so it never goes through
 * CamelReadModel's alias generator.
 * ------------------------------------------------------------------------- */

export interface LessonPlanContent {
  objectives: string[];
  introduction: string;
  core_concepts: string[];
  classroom_discussion: string[];
  assessment: string[];
  homework: string;
}

export interface ScriptSection {
  heading: string;
  script: string;
  discussion_prompt: string;
}

export interface TeachingScriptContent {
  opening: string;
  sections: ScriptSection[];
  closing: string;
}

export type QuestionKind = "mcq" | "short_answer" | "long_answer" | "hots";

export interface QuestionOption {
  label: string;
  text: string;
  is_correct: boolean;
}

export interface QuestionItem {
  type: QuestionKind;
  difficulty: QuestionDifficulty;
  question_text: string;
  options: QuestionOption[] | null;
  answer: string;
  explanation: string | null;
}

export interface QuestionSetContent {
  questions: QuestionItem[];
}

export type WorksheetSectionType = "fill_blank" | "true_false" | "match";

export interface WorksheetSection {
  type: WorksheetSectionType;
  fill_blank_items: { text: string; answer: string }[];
  true_false_items: { statement: string; is_true: boolean }[];
  match_items: { left: string; right: string }[];
}

export interface WorksheetContent {
  sections: WorksheetSection[];
}

/** Recursive, matching `mind_maps.structure` jsonb. Note the backend *asks* the
 * model for a flattened three-level shape and folds it into this one — see
 * apps/api/app/ai/prompts/mind_map.py for why. */
export interface MindMapNode {
  id: string;
  label: string;
  children: MindMapNode[];
}

export type SlideLayout = "title" | "bullets" | "diagram" | "image_caption";

export interface Slide {
  layout: SlideLayout;
  title: string;
  body: string[];
  speaker_notes: string;
}

/** Slide counts are constrained to 5 | 10 | 15 by `presentations.slide_count`. */
export type PresentationVersion = "5" | "10" | "15";

export interface PresentationContent {
  versions: Record<PresentationVersion, Slide[]>;
}

export const PRESENTATION_VERSIONS: PresentationVersion[] = ["5", "10", "15"];

/** Placeholder payload from a resource type with no generator yet (audio →
 * Phase 5). Every `*View` should handle it rather than assume real content. */
export interface PlaceholderContent {
  placeholder: true;
  note: string;
}

export function isPlaceholder(
  content: Record<string, unknown>,
): content is PlaceholderContent & Record<string, unknown> {
  return content.placeholder === true;
}

/** Type-specific re-roll knobs for `POST /resources/{id}/regenerate`. */
export interface RegenerateResourceRequest {
  params: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Library — saved lessons
// ---------------------------------------------------------------------------

export interface SavedLesson {
  id: string;
  requestId: string;
  note: string | null;
  savedAt: string;
  classDisplayName: string;
  subjectName: string;
  chapterName: string;
  language: AppLanguage;
  duration: DurationOption;
  teachingMode: TeachingMode;
}

export interface SavedLessonsPage {
  items: SavedLesson[];
  nextCursor: string | null;
}

// ---------------------------------------------------------------------------
// Audio narration
// ---------------------------------------------------------------------------

export type AudioDuration = "1" | "3" | "5";

export interface AudioContent {
  variants: Record<AudioDuration, string>;
}
