import enum


class UserRole(enum.StrEnum):
    teacher = "teacher"
    school_admin = "school_admin"
    super_admin = "super_admin"


class AppLanguage(enum.StrEnum):
    en = "en"
    hi = "hi"
    hinglish = "hinglish"


class DurationOption(enum.StrEnum):
    thirty = "30"
    forty = "40"
    sixty = "60"


class TeachingMode(enum.StrEnum):
    story = "story"
    activity = "activity"
    exam = "exam"
    concept = "concept"
    quick_revision = "quick_revision"


class KitStatus(enum.StrEnum):
    pending = "pending"
    generating = "generating"
    partial = "partial"
    complete = "complete"
    failed = "failed"


class ResourceType(enum.StrEnum):
    lesson_plan = "lesson_plan"
    teaching_script = "teaching_script"
    blackboard_notes = "blackboard_notes"
    local_context = "local_context"
    activities = "activities"
    questions = "questions"
    previous_year_questions = "previous_year_questions"
    worksheet = "worksheet"
    presentation = "presentation"
    mind_map = "mind_map"
    flowchart = "flowchart"
    diagram = "diagram"
    audio = "audio"
    animation = "animation"


# Resources generated by default for every kit until the rest leave "designed
# but not implemented" — mirrors packages/shared-types' MVP_RESOURCE_TYPES.
MVP_RESOURCE_TYPES: list[ResourceType] = [
    ResourceType.lesson_plan,
    ResourceType.teaching_script,
    ResourceType.questions,
    ResourceType.worksheet,
    ResourceType.presentation,
    ResourceType.mind_map,
    ResourceType.audio,
]


class QuestionType(enum.StrEnum):
    mcq = "mcq"
    short_answer = "short_answer"
    long_answer = "long_answer"
    hots = "hots"


class Difficulty(enum.StrEnum):
    easy = "easy"
    moderate = "moderate"
    advanced = "advanced"


class AnalyticsEventType(enum.StrEnum):
    search = "search"
    kit_generated = "kit_generated"
    resource_viewed = "resource_viewed"
    resource_downloaded = "resource_downloaded"
    resource_regenerated = "resource_regenerated"
    cache_hit = "cache_hit"
    cache_miss = "cache_miss"
