import enum

from sqlalchemy import Enum as SAEnum


class UserRole(enum.StrEnum):
    teacher = "teacher"
    school_admin = "school_admin"
    super_admin = "super_admin"


class AppLanguage(enum.StrEnum):
    en = "en"
    hi = "hi"
    hinglish = "hinglish"


class DurationOption(enum.StrEnum):
    thirty = "30"
    forty = "40"
    sixty = "60"


class TeachingMode(enum.StrEnum):
    story = "story"
    activity = "activity"
    exam = "exam"
    concept = "concept"
    quick_revision = "quick_revision"


class KitStatus(enum.StrEnum):
    pending = "pending"
    generating = "generating"
    partial = "partial"
    complete = "complete"
    failed = "failed"


class ResourceType(enum.StrEnum):
    lesson_plan = "lesson_plan"
    teaching_script = "teaching_script"
    blackboard_notes = "blackboard_notes"
    local_context = "local_context"
    activities = "activities"
    questions = "questions"
    previous_year_questions = "previous_year_questions"
    worksheet = "worksheet"
    presentation = "presentation"
    mind_map = "mind_map"
    flowchart = "flowchart"
    diagram = "diagram"
    audio = "audio"
    animation = "animation"


# Resources generated by default for every kit until the rest leave "designed
# but not implemented" — mirrors packages/shared-types' MVP_RESOURCE_TYPES.
MVP_RESOURCE_TYPES: list[ResourceType] = [
    ResourceType.lesson_plan,
    ResourceType.teaching_script,
    ResourceType.questions,
    ResourceType.worksheet,
    ResourceType.presentation,
    ResourceType.mind_map,
    ResourceType.audio,
]


class QuestionType(enum.StrEnum):
    mcq = "mcq"
    short_answer = "short_answer"
    long_answer = "long_answer"
    hots = "hots"


class Difficulty(enum.StrEnum):
    easy = "easy"
    moderate = "moderate"
    advanced = "advanced"


class AnalyticsEventType(enum.StrEnum):
    search = "search"
    kit_generated = "kit_generated"
    resource_viewed = "resource_viewed"
    resource_downloaded = "resource_downloaded"
    resource_regenerated = "resource_regenerated"
    cache_hit = "cache_hit"
    cache_miss = "cache_miss"


def db_enum(enum_cls: type[enum.Enum], name: str) -> SAEnum:
    """A Postgres enum column that persists the member's *value*, not its name.

    SQLAlchemy's default is to store `member.name`, while the Alembic
    migrations create each Postgres type from `member.value`. For every enum
    here except `DurationOption` those happen to be identical, which is why
    the mismatch stayed invisible: `DurationOption.forty` has value "40" but
    name "forty", so inserting one raised
    `invalid input value for enum duration_option: "forty"` the first time a
    request hit real Postgres.

    SQLite can't catch this — it renders an Enum as VARCHAR plus a CHECK
    constraint built from the same names it then stores, so it is
    self-consistent whichever side is wrong. Routing every enum column through
    this helper means a future member whose name differs from its value can't
    reintroduce the bug.
    """
    return SAEnum(enum_cls, name=name, values_callable=lambda e: [m.value for m in e])
